
title: Liam May Design and computer sciense portfolio
locale: en_NZ
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Liam
  avatar: bio-photo.jpg
  bio: "This is a portfolio of my designa nd computer science work"
  email: n/a
  # Do not include the @ symbol in your Twitter username
  
  linkedin: #username
  

